{{- if .Values.services.plex.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: {{ .Values.common.namespace }}
  labels:
    app.kubernetes.io/name: plex
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.services.plex.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: plex
  template:
    metadata:
      labels:
        app.kubernetes.io/name: plex
    spec:
      containers:
        - name: plex
          image: "{{ .Values.services.plex.image.repository }}:{{ .Values.services.plex.image.tag }}"
          imagePullPolicy: {{ .Values.services.plex.image.pullPolicy }}
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "{{ .Values.common.tz }}"
          ports:
            - name: http
              containerPort: {{ .Values.services.plex.ports.http }}
              protocol: TCP
          volumeMounts:
            - name: plex-config
              mountPath: "/config"
            - name: smb
              subPath: "{{ .Values.services.plex.library }}"
              mountPath: /library
      volumes:
        - name: smb
          persistentVolumeClaim:
            claimName: {{ .Values.storage.smb.pvcClaimName }}
        - name: plex-config
          hostPath:
            path: "{{ .Values.services.plex.config }}"
            type: Directory
        # - name: library
        #   hostPath:
        #     path: "{{ .Values.services.plex.library }}"
        #     type: Directory
{{- end }}
